### PR TITLE
Make siteId property required

### LINKED ISSUE #235: According to TypeScript, siteId is a required property for the createInstance config parameter
**Describe the bug**
According to TypeScript, siteId is a required property for the config parameter in `createInstance` while, according to the docs, siteId is optional (whose default value is 1). Given the contradiction, either the TypeScript or the docs are incorrect.

**To Reproduce**
1. Call `createInstance` with `{ urlBase: 'https://LINK.TO.DOMAIN' }`
2. See a TypeScript error explaining siteId is required
3. See the [Usage](https://github.com/Amsterdam/matomo-tracker/tree/master/packages/react#usage) section of the React docs and notice `siteId` is said to be optional
4. Be confused 🤔 

**Expected behavior**
TypeScript and the docs live in harmony.

**Screenshots**
Screen Shot 2020-09-01 at 12 04 59 AM

**Desktop (please complete the following information):**
 - Version: 0.2.0

### PR DESCRIPTION
**Pull request by AryanJ-NYC**
Closes #235

Before opening a pull request, please ensure:

- [x] You've added or updated the [README.md](../blob/master/README.md) if needed
- [x] Your code has the necessary tests written
- [x] You have updated the [CHANGELOG.md unreleased sections](../blob/master/CHANGELOG.md)

### CODE REVIEW

**Review by jonkoops — CHANGES_REQUESTED** [review]
In `MatomoTracker` there is a line that pushes the `siteId`, this statement will have to be conditional:

```ts
if (siteId !== undefined) {
  this.pushInstruction('setSiteId', siteId)
}
```

**Comment by AryanJ-NYC** [comment]
In the constructor for MatomoTracker, we have:

https://github.com/Amsterdam/matomo-tracker/blob/d6e11daead97e415ac11781984646fc020215990/packages/js/src/MatomoTracker.ts#L19

`defaultOptions` here stems from `./constants` and includes `siteId: 1` which makes sure `siteId` is populated:
https://github.com/Amsterdam/matomo-tracker/blob/d6e11daead97e415ac11781984646fc020215990/packages/js/src/constants.ts#L3

In my opinion, we may instead want to throw an error in the constructor if `options.siteId` is _somehow_ not populated (and hopefully this error never throws).

Thoughts?

**Comment by jonkoops** [comment]
@AryanJ-NYC Looking at the documentation of Matomo it seems that the `siteId` is pretty explicitly mentioned as part of the bootstrapping process. In that regard I think it makes sense that `siteId` is a required property in the interface.

I would propose we get rid of the default value to align the implementation with the type definition. I also agree that this should throw an exception (like urlBase) for users that might not be using TypeScript in their application.

**Comment by AryanJ-NYC** [comment]
Got it. That makes sense, too. I can do that. 

But just to be explicit, that'd be a breaking change (which should be expected this early in a project) as there may be folks using this library that didn't explicitly set `siteId` to 1 since that was the default.

I'm not against that but instead wanted to explicitly point it out to make sure everyone is on the same page.

If so, I can make that change later tonight.

**Comment by jonkoops** [comment]
Yeah, that sounds good to me. We're indeed still in an early stage of this project so we will still be introducing breaking changes in pre-1.0 versions. I'll make sure that this change will be added to a minor version as per semver specification.

Could you also add a `[BREAKING]` tag to the changelog for it?

File: packages/js/src/constants.ts [hunk 1]
```diff
@@ -1,8 +1,4 @@
-export const defaultOptions = {
-  urlBase: null,
-  siteId: 1,
-}
-
+// eslint-disable-next-line import/prefer-default-export
```
Comment (AryanJ-NYC) [inline packages/js/src/constants.ts:1]: @jonkoops I deleted the `defaultOptions` object here as it no longer made sense to keep it (it'd likely cause a ton of confusion since both `urlBase` and `siteId` would be `null` or `undefined`. That made the `import/prefer-default-export` rule kick in. Would you like me to make `TRACK_TYPES` the default export or leave as is?

Comment (jonkoops) [reply packages/js/src/constants.ts:1]: Let's leave it as is. Since this file is for all types of constants we can keep the named export.

File: packages/js/src/MatomoTracker.test.ts [hunk 2]
```diff
@@ -3,6 +3,18 @@ import MatomoTracker from './MatomoTracker'
 const URL_BASE = 'https://example.com'
```
Comment (jonkoops) [inline packages/js/src/MatomoTracker.test.ts:3]: Thanks for adding these tests as well :ok_hand:

File: packages/js/src/MatomoTracker.test.ts [hunk 3]
```diff
@@ -3,6 +3,18 @@ import MatomoTracker from './MatomoTracker'
...
+    // eslint-disable-next-line
+    // @ts-expect-error
+    expect(() => new MatomoTracker({ siteId: 1 })).toThrowError()
+  })
+
+  it('throws an error if no siteId is passed in options', () => {
+    // eslint-disable-next-line
+    // @ts-expect-error
+    expect(() => new MatomoTracker({ urlBase: URL_BASE })).toThrowError()
+  })
```
Comment (jonkoops) [inline packages/js/src/MatomoTracker.test.ts:16]: Instead of adding these comments to disable ESLint and the TypeScript compiler you can use `as UserOptions` to force the argument to be accepted.

```suggestion
  it('throws an error if no urlBase is passed in options', () => {
    expect(() => new MatomoTracker({ siteId: 1 } as UserOptions)).toThrowError()
  })

  it('throws an error if no siteId is passed in options', () => {
    expect(() => new MatomoTracker({ urlBase: URL_BASE } as UserOptions)).toThrowError()
  })
```

**Review by jonkoops — CHANGES_REQUESTED** [review]

File: packages/js/src/MatomoTracker.test.ts (hunk 3 above)
Comment (AryanJ-NYC) [reply packages/js/src/MatomoTracker.test.ts]: Good call. Done.
